In [1]:
import numpy as np
x=np.array([3,1,2])
h=np.array([3,2,1])
print(np.convolve(x,h))

[ 9  9 11  5  2]


In [2]:
def convolution(x,h):
    size=max(len(x), len(h))
  #  print(x.shape)
    if(len(x)>len(h)):
        result = np.zeros(x.shape)
        result[:h.shape[0]] = h
        h=result
    if(len(h)>len(x)):
        result = np.zeros(h.shape)
        result[:x.shape[0]] = x
        x=result
    result=np.zeros(len(x)+len(h)-1)
    for n in range(len(x)):
        for k in range(len(h)):
            #print(k)
           
              #  print("k: ",k)
              #  print(x[k]*h[n-k])
            result[n+k]=result[n+k]+x[n]*h[k]
          
        
    return result

In [3]:
#a
x=np.array([0,1,2,3])
h=np.array([1,1,1,1])
print(convolution(x,h))

[0. 1. 3. 6. 6. 5. 3.]


In [4]:
#b
x=np.array([0,1,2,3])
h=np.array([1])
print(convolution(x,h))

[0. 1. 2. 3. 0. 0. 0.]


In [5]:
#c
x=np.array([0,1,2,3])
h=np.array([0,1,2,3])
print(convolution(x,h))

[ 0.  0.  1.  4. 10. 12.  9.]


In [6]:
#d
x=np.array([1,0,1,2,3])
h=np.array([1,2])
print(convolution(x,h))

[1. 2. 1. 4. 7. 6. 0. 0. 0.]
